/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccessCodeRouteImport } from './routes/$accessCode'

const AccessCodeRoute = AccessCodeRouteImport.update({
  id: '/$accessCode',
  path: '/$accessCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$accessCode': typeof AccessCodeRoute
}
export interface FileRoutesByTo {
  '/$accessCode': typeof AccessCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$accessCode': typeof AccessCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$accessCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/$accessCode'
  id: '__root__' | '/$accessCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccessCodeRoute: typeof AccessCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$accessCode': {
      id: '/$accessCode'
      path: '/$accessCode'
      fullPath: '/$accessCode'
      preLoaderRoute: typeof AccessCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AccessCodeRoute: AccessCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
